name: Build package on development branch
run-name: Build initiated by ${{ github.actor }}
on:
  pull_request:
    types: [closed]
    branches:
      - development
jobs:
  build:
    if: github.event.pull_request.merged == true && github.base_ref == 'development'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: 'development'
    - name: Setup Java 17 and Maven
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: 'pom.xml'
    - name: Create Maven settings.xml
      run: |
        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"' > settings.xml
        echo '  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' >> settings.xml
        echo '  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0' >> settings.xml
        echo '                      http://maven.apache.org/xsd/settings-1.0.0.xsd">' >> settings.xml
        echo '' >> settings.xml
        echo '  <activeProfiles>' >> settings.xml
        echo '    <activeProfile>github</activeProfile>' >> settings.xml
        echo '  </activeProfiles>' >> settings.xml
        echo '' >> settings.xml
        echo '  <profiles>' >> settings.xml
        echo '    <profile>' >> settings.xml
        echo '      <id>github</id>' >> settings.xml
        echo '      <repositories>' >> settings.xml
        echo '        <repository>' >> settings.xml
        echo '          <id>central</id>' >> settings.xml
        echo '          <url>https://repo1.maven.org/maven2</url>' >> settings.xml
        echo '        </repository>' >> settings.xml
        echo '        <repository>' >> settings.xml
        echo '          <id>github</id>' >> settings.xml
        echo '          <url>https://maven.pkg.github.com/${{ github.repository_owner }}/HelloEnv</url>' >> settings.xml
        echo '          <snapshots>' >> settings.xml
        echo '            <enabled>true</enabled>' >> settings.xml
        echo '          </snapshots>' >> settings.xml
        echo '        </repository>' >> settings.xml
        echo '      </repositories>' >> settings.xml
        echo '    </profile>' >> settings.xml
        echo '  </profiles>' >> settings.xml
        echo '' >> settings.xml
        echo '  <servers>' >> settings.xml
        echo '    <server>' >> settings.xml
        echo '      <id>github</id>' >> settings.xml
        echo '      <username>${{ secrets.USERNAME }}</username>' >> settings.xml
        echo '      <password>${{ secrets.GITHUB_TOKEN }}</password>' >> settings.xml
        echo '    </server>' >> settings.xml
        echo '  </servers>' >> settings.xml
        echo '</settings>' >> settings.xml
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build with Maven
      env: 
        UAT_ENVIRONMENT_VARIABLE: ${{ vars.UAT_ENVIRONMENT_VARIABLE }}
        SIT_ENVIRONMENT_VARIABLE: ${{ vars.SIT_ENVIRONMENT_VARIABLE }}
        DEV_ENVIRONMENT_VARIABLE: ${{ vars.DEV_ENVIRONMENT_VARIABLE }}
      run: |
          echo "environment=$DEV_ENVIRONMENT_VARIABLE" > src/main/resources/dev.properties
          echo "environment=$SIT_ENVIRONMENT_VARIABLE" > src/main/resources/sit.properties
          echo "environment=$UAT_ENVIRONMENT_VARIABLE" > src/main/resources/uat.properties
          mvn clean package
    - name: Sample Deployment
      run: |
          java -Denvironment.file=dev.properties -jar $(ls target/helloenv-*.jar)
          java -Denvironment.file=sit.properties -jar $(ls target/helloenv-*.jar)
          java -Denvironment.file=uat.properties -jar $(ls target/helloenv-*.jar)
    - name: Publish to GitHub Packages
      run: mvn deploy
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
