name: Build package on release branches
run-name: Build initiated by ${{ github.actor }}
on:
  create:
    branches:
      - 'release/**'
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/release/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Print Working Dir
        run: |
            ls -lah
             
