name: Build package on release branches
run-name: Build initiated by ${{ github.actor }}
on:
  create:
    branches:
      - 'release/**'
  pull_request:
     types: [closed]
     branches:
       - release/**
  push:
    branches:
      - "release/**"
jobs:
  build:
    runs-on: ubuntu-latest
    if: >
        (github.ref_type == 'branch' && startsWith(github.ref, 'refs/heads/release/')) || 
        (github.event_name == 'pull_request' && github.event.pull_request.merged == true && startsWith(github.event.pull_request.base.ref, 'release/'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Extract Version from Branch Name
        id: extract_version
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | sed 's|refs/heads/release/v||')" >> "$GITHUB_ENV"
          echo "Extracted version is $VERSION"
      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet
      - name: Update pom.xml
        run: |
          echo $VERSION
          xmlstarlet edit --inplace --update "/project/version" -value ${{ steps.extract_version.outputs.VERSION }} pom.xml
      - name: Print Working Dir
        run: |
            cat pom.xml